package fr.iut2.sil4.data;

import java.util.List;

import org.apache.torque.criteria.Criteria;

/**
 * Note Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sun Feb 23 17:07:40 CET 2014]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class AbscencePeer
    extends fr.iut2.sil4.data.BaseAbscencePeer
{
	public static List<Abscence> doSelectAll() throws Exception {
		Criteria crit = new Criteria();
		return doSelect(crit);
	}
	
	
	
	public static List<Abscence> getAbscences(int studentId) throws Exception {
		
		Criteria crit = new Criteria();	
		crit.and(STUDENT_ID,studentId,Criteria.EQUAL);
		List<Abscence> abscences = doSelect(crit);
		
		return abscences;
	}


}
