package fr.iut2.sil4.data;

/**
 * Note Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sun Feb 23 17:07:40 CET 2014]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class AbscencePeer
    extends fr.iut2.sil4.data.BaseAbscencePeer
{

}
