package fr.iut2.sil4.data;


/**
 * Maps ResultSet rows into Abscence objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sun Feb 23 17:07:41 CET 2014]
 *
 */
public class AbscenceRecordMapper extends BaseAbscenceRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1393171661404L;



}
