package fr.iut2.sil4.data;

import java.util.List;

import org.apache.torque.criteria.Criteria;

/**
 * Note Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sun Feb 23 13:54:10 CET 2014]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class NotePeer
    extends fr.iut2.sil4.data.BaseNotePeer
{
	public static List<Note> doSelectAll() throws Exception {
		Criteria crit = new Criteria();
		return doSelect(crit);
	}

}
