package fr.iut2.sil4.data;


/**
 * Maps ResultSet rows into Note objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sun Feb 23 13:54:11 CET 2014]
 *
 */
public class NoteRecordMapper extends BaseNoteRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1393160051327L;



}
