package fr.iut2.sil4.data;

/**
 * Note Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sun Feb 23 13:54:10 CET 2014]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class NotePeerImpl
    extends fr.iut2.sil4.data.BaseNotePeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1393160050912L;



}
