package fr.iut2.sil4.data;


/**
 * Maps ResultSet rows into Student objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jan 06 15:59:14 CET 2014]
 *
 */
public class StudentRecordMapper extends BaseStudentRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1389020354581L;



}
