package fr.iut2.sil4.data;

import java.util.List;

import org.apache.torque.criteria.Criteria;

/**
 * Student Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jan 06 15:59:14 CET 2014]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class StudentPeer
    extends fr.iut2.sil4.data.BaseStudentPeer
{
	public static List<Student> doSelectAll() throws Exception {
		Criteria crit = new Criteria();
		return doSelect(crit);
	}
	
}
