package fr.iut2.sil4.data;

/**
 * Student Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jan 06 15:59:14 CET 2014]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class StudentPeerImpl
    extends fr.iut2.sil4.data.BaseStudentPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1389020354335L;



}
