package fr.iut2.sil4.data;


/**
 * Maps ResultSet rows into User objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jan 20 13:54:22 CET 2014]
 *
 */
public class UserRecordMapper extends BaseUserRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1390222462695L;



}
