package fr.iut2.sil4.data;

/**
 * Group Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Feb 22 18:25:17 CET 2014]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class UsergroupPeerImpl
    extends fr.iut2.sil4.data.BaseUsergroupPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1393089917042L;



}
