package fr.iut2.sil4.data;


/**
 * Group Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Feb 22 18:25:16 CET 2014]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public  class Usergroup
    extends fr.iut2.sil4.data.BaseUsergroup
{
    /** Serial version */
    private static final long serialVersionUID = 1393089916371L;



}
