package fr.iut2.sil4.data;

import java.util.List;

import org.apache.torque.criteria.Criteria;

/**
 * User Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jan 20 13:54:22 CET 2014]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class UserPeer
    extends fr.iut2.sil4.data.BaseUserPeer
{
	public static Boolean doConnect(String username, String passwd) throws Exception {
		
		Criteria crit = new Criteria();	
		crit.and(USER_NAME,username,Criteria.EQUAL);
		User user = doSelect(crit).get(0);
		
		return user.getPassword().equals(passwd);
	}
}
