package fr.iut2.sil4.data;


/**
 * Maps ResultSet rows into Usergroup objects.
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Feb 22 18:25:17 CET 2014]
 *
 */
public class UsergroupRecordMapper extends BaseUsergroupRecordMapper
{
    /** Serial version */
    private static final long serialVersionUID = 1393089917416L;



}
