package fr.iut2.sil4.data;

/**
 * Group Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Feb 22 18:25:16 CET 2014]
 *
 * This class provides static wrappers for the peer implementation classes.
 * This class will only be generated as long as it does not already exist
 * in the output directory.
 */

public class UsergroupPeer
    extends fr.iut2.sil4.data.BaseUsergroupPeer
{

}
