package fr.iut2.sil4.data;

/**
 * User Table
 *
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Jan 20 13:54:22 CET 2014]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class UserPeerImpl
    extends fr.iut2.sil4.data.BaseUserPeerImpl
{
    /** Serial version */
    private static final long serialVersionUID = 1390222462391L;



}
